# Generated by Django 3.2.25 on 2024-12-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0003_auto_20241221_2348'),
        ('tasks', '0003_auto_20241221_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_attendee',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='attendee.Attendee'),
        ),
    ]
