# Generated by Django 3.2.25 on 2024-12-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0003_auto_20241221_2348'),
        ('tasks', '0004_alter_task_assigned_attendee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_attendee',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='attendee.attendee'),
        ),
    ]
