# Generated by Django 3.2.25 on 2024-12-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0003_auto_20241221_2348'),
        ('tasks', '0008_auto_20241222_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_attendee',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_attendee',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='attendee.Attendee'),
        ),
    ]
