# Generated by Django 3.2.25 on 2024-12-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('events', '0001_initial'),
        ('attendee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='events',
            field=models.ManyToManyField(related_name='event_attendees', to='events.Event'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='tasks',
            field=models.ManyToManyField(related_name='assigned_tasks', to='tasks.Task'),
        ),
    ]
