# Generated by Django 3.2.25 on 2024-12-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_assigned_attendee'),
        ('events', '0001_initial'),
        ('attendee', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='event_attendees', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='tasks.Task'),
        ),
    ]
