# Generated by Django 3.2.25 on 2024-12-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('attendee', '0003_auto_20241221_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='attendee_events', to='events.Event'),
        ),
    ]
