# Generated by Django 3.2.25 on 2024-12-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0004_alter_attendee_events'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='event_attendees', to='attendee.Attendee'),
        ),
    ]
